# Queries para criação do banco de dados da clinica CLimed para ACH2025 em MySQL
#
# Heitor Lopes Bianchi - 10258730
# Marina Gonçalves do Nascimento - 10367291 

# criar BD

CREATE SCHEMA ClIMED;
USE CLIMED;

# Criar tabelas

CREATE TABLE AGENDA (
    IdAgenda  INT NOT NULL, 
    DiaSemana VARCHAR(50) NOT NULL,  
    HoraInicio TIME (0) NOT NULL,   
    HoraFIm TIME (0) NOT NULL,   
    CRM VARCHAR(50) NOT NULL,  
    PRIMARY KEY (IdAgenda)
) ENGINE = innodb;

CREATE TABLE MEDICO (
    CRM  VARCHAR(50) NOT NULL, 
    NomeM VARCHAR(50) NOT NULL,  
    TelefoneM VARCHAR(50) NOT NULL,  
    Percentual INT NOT NULL,
    PRIMARY KEY (CRM)
) ENGINE = innodb;

CREATE TABLE EXERCEESP (
    CRM  VARCHAR(50) NOT NULL, 
    IdEsp INT NOT NULL,
    PRIMARY KEY (IdEsp)
) ENGINE = innodb;

CREATE TABLE ESPECIALIDADE (
    IdEsp INT NOT NULL,
    NomeE VARCHAR(50) NOT NULL,  
    Indice VARCHAR(50) NOT NULL, 
    PRIMARY KEY (IdEsp)
) ENGINE = innodb;

CREATE TABLE PACIENTE (
    IdPac INT NOT NULL,  
    CPF VARCHAR(50) NOT NULL, 
    NomeP VARCHAR(50) NOT NULL, 
    TelefonePac VARCHAR(50) NOT NULL, 
    Endereco VARCHAR(50) NOT NULL, 
    Idade INT NOT NULL, 
    Sexo VARCHAR(50) NOT NULL, 
    PRIMARY KEY (IdPac)
) ENGINE = innodb;

CREATE TABLE CONSULTA (
    IdCon  INT NOT NULL, 
    CRM  VARCHAR(50) NOT NULL,  
    IdEsp INT NOT NULL,
    IdPac INT NOT NULL,  
    Data DATE NOT NULL,  
    HoraInicCon TIME (0) NOT NULL, 
    HoraFimCon TIME (0) NOT NULL, 
    Pagou VARCHAR(50) NOT NULL, 
    ValorPago INT NOT NULL, 
    FormaPagamento VARCHAR(50) NOT NULL, 
    PRIMARY KEY (IdCon)
) ENGINE = innodb;

CREATE TABLE DOENCA (
    IdDoenca  INT NOT NULL, 
    NomeD VARCHAR(50) NOT NULL, 
    PRIMARY KEY (IdDoenca)
) ENGINE = innodb;

CREATE TABLE DIAGNOSTICO (
    IdDiagnostico  INT NOT NULL, 
    IdCon  INT NOT NULL, 
    TratamentoRecomendado VARCHAR(50) NOT NULL, 
    RemediosReceitados VARCHAR(50) NOT NULL, 
    Observacoes VARCHAR(50) NOT NULL 
) ENGINE = innodb;

CREATE TABLE DIAGNOSTICA (
    IdDiagnostico  INT NOT NULL, 
    IdDoenca INT NOT NULL, 
    PRIMARY KEY (IdDiagnostico)
) ENGINE = innodb;

# Criar FOREIGN KEYs

ALTER TABLE AGENDA ADD CONSTRAINT fk_CRM_I  FOREIGN KEY (CRM) REFERENCES MEDICO(CRM);

ALTER TABLE EXERCEESP ADD CONSTRAINT fk_CRM_II  FOREIGN KEY (CRM) REFERENCES MEDICO(CRM);
ALTER TABLE EXERCEESP ADD CONSTRAINT fk_IdEsp_I  FOREIGN KEY (IdEsp) REFERENCES ESPECIALIDADE(IdEsp);

ALTER TABLE CONSULTA ADD CONSTRAINT fk_CRM_III  FOREIGN KEY (CRM) REFERENCES MEDICO(CRM);
ALTER TABLE CONSULTA ADD CONSTRAINT fk_IdPac  FOREIGN KEY (IdPac) REFERENCES PACIENTE(IdPac);
ALTER TABLE CONSULTA ADD CONSTRAINT fk_IdEsp_II  FOREIGN KEY (IdEsp) REFERENCES ESPECIALIDADE(IdEsp);

ALTER TABLE DIAGNOSTICA ADD CONSTRAINT fk_IdDiagnostico  FOREIGN KEY (IdDiagnostico) REFERENCES DIAGNOSTICO(IdDiagnostico);
ALTER TABLE DIAGNOSTICA ADD CONSTRAINT fk_IdDoenca  FOREIGN KEY (IdDoenca) REFERENCES DOENCA(IdDoenca);

ALTER TABLE DIAGNOSTICO ADD CONSTRAINT fk_IdCon  FOREIGN KEY (IdCon) REFERENCES CONSULTA(IdCon);